### ISSUE TITLE
Port Switch Crates from Strawberry Jam

### ISSUE THREAD

**Issue by catapillie** [CommunalHelper/Batteries#3]
Initially marked to be ported in [Communal Helper](https://github.com/CommunalHelper/CommunalHelper), these three entities are going to be ported here, since they reference code from this helper.

* **Switch Crate**
    - [ ] Port implementation from `SwitchCrate.cs`
    - [ ] Write Lönn plugin
    - [ ] Copy Ahorn plugin
* **Switch Crate Holder**
    - [ ] Port implementation from `SwitchCrateHolder.cs`
    - [ ] Write Lönn plugin
    - [ ] Copy Ahorn plugin
* **Switch Door**
    - [ ] Port implementation from `SwitchDoor.cs`
    - [ ] Write Lönn plugin
    - [ ] Copy Ahorn plugin

**Comment by bigkahuna443** [comment]
These are all slightly special-cased in ways that don't really fit in the general Batteries helper. We may revisit this if something comes up but I'll close this for now.
